version: '3'

services:
  db:
    container_name: db
    image: postgres:10.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - app
  front-end:
    container_name: front-end
    depends_on:
      - back-end
    build:
      context: front-end
    ports:
      - "3000:80"
    networks:
      - app
  back-end:
    container_name: back-end
    depends_on:
      - db
    build:
      context: back-end
    ports:
      - "5000:3000"
    networks:
      - app


networks:
  app:
    driver: bridge